[2023-10-26T18:12:38.992+0800] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_minio_v2.sensor_minio_s3 scheduled__2023-10-24T16:00:00+00:00 [queued]>
[2023-10-26T18:12:39.013+0800] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_minio_v2.sensor_minio_s3 scheduled__2023-10-24T16:00:00+00:00 [queued]>
[2023-10-26T18:12:39.014+0800] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2023-10-26T18:12:39.034+0800] {taskinstance.py:1380} INFO - Executing <Task(S3KeySensor): sensor_minio_s3> on 2023-10-24 16:00:00+00:00
[2023-10-26T18:12:39.044+0800] {standard_task_runner.py:57} INFO - Started process 1519 to run task
[2023-10-26T18:12:39.065+0800] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_minio_v2', 'sensor_minio_s3', 'scheduled__2023-10-24T16:00:00+00:00', '--job-id', '640', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_minio.py', '--cfg-path', '/tmp/tmprfpp66cc']
[2023-10-26T18:12:39.076+0800] {standard_task_runner.py:85} INFO - Job 640: Subtask sensor_minio_s3
[2023-10-26T18:12:39.207+0800] {task_command.py:415} INFO - Running <TaskInstance: dag_with_minio_v2.sensor_minio_s3 scheduled__2023-10-24T16:00:00+00:00 [running]> on host 26a4c5bc8d30
[2023-10-26T18:12:39.385+0800] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='joshua881117@gmail.com' AIRFLOW_CTX_DAG_OWNER='Joshua Lin' AIRFLOW_CTX_DAG_ID='dag_with_minio_v2' AIRFLOW_CTX_TASK_ID='sensor_minio_s3' AIRFLOW_CTX_EXECUTION_DATE='2023-10-24T16:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-24T16:00:00+00:00'
[2023-10-26T18:12:39.390+0800] {s3.py:106} INFO - Poking for key : s3://***/result.csv
[2023-10-26T18:12:39.423+0800] {base.py:73} INFO - Using connection ID 'minio_conn' for task execution.
[2023-10-26T18:12:39.426+0800] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2023-10-26T18:12:46.357+0800] {s3.py:106} INFO - Poking for key : s3://***/result.csv
[2023-10-26T18:12:51.421+0800] {s3.py:106} INFO - Poking for key : s3://***/result.csv
[2023-10-26T18:12:56.499+0800] {s3.py:106} INFO - Poking for key : s3://***/result.csv
[2023-10-26T18:13:01.557+0800] {s3.py:106} INFO - Poking for key : s3://***/result.csv
[2023-10-26T18:13:06.611+0800] {s3.py:106} INFO - Poking for key : s3://***/result.csv
[2023-10-26T18:13:11.664+0800] {s3.py:106} INFO - Poking for key : s3://***/result.csv
[2023-10-26T18:13:11.681+0800] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/sensors/s3.py", line 144, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 274, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 32.28768468101043 seconds exceeds the specified timeout of 30.0.
[2023-10-26T18:13:11.727+0800] {taskinstance.py:1398} INFO - Immediate failure requested. Marking task as FAILED. dag_id=dag_with_minio_v2, task_id=sensor_minio_s3, execution_date=20231024T160000, start_date=20231026T101238, end_date=20231026T101311
[2023-10-26T18:13:11.764+0800] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2023-10-26T18:13:11.765+0800] {email.py:270} INFO - Email alerting: attempt 1
[2023-10-26T18:13:13.215+0800] {email.py:282} INFO - Sent an alert email to ['joshua881117@gmail.com']
[2023-10-26T18:13:15.030+0800] {standard_task_runner.py:104} ERROR - Failed to execute job 640 for task sensor_minio_s3 (Sensor has timed out; run duration of 32.28768468101043 seconds exceeds the specified timeout of 30.0.; 1519)
[2023-10-26T18:13:15.111+0800] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-26T18:13:15.145+0800] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
